name: Deploy Guardians

# Run on pushes to main or PRs
on:
  # Launches when manually triggered with the new workflow_dispatch event
  workflow_dispatch:
    branches:
      - main

env:
  REPO_NAME_ALPHANUMERIC: claiming-app-data
  STAGING_BUCKET_NAME: ${{ secrets.STAGING_BUCKET_NAME }}
  PROD_BUCKET_NAME: ${{ secrets.PROD_BUCKET_NAME }}
  INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}

jobs:

  deploy:
    name: Deployment
    runs-on: ubuntu-latest

    steps:

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Remove broken apt repos [Ubuntu]
        if: ${{ matrix.os }} == 'ubuntu-latest'
        run: |
          for apt_file in `grep -lr microsoft /etc/apt/sources.list.d/`; do sudo rm $apt_file; done

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Configure python environment
        run: |
          sudo apt-get update
          sudo apt-get install --yes --quiet inkscape
          pip install -r requirements.txt

      - name: 'Process guardian data'
        if: github.ref == 'refs/heads/main'
        run: |
          cd guardians
          python import_guardians.py
          cd ..

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      # Script to deploy to staging environment
      - name: 'Deploy to S3: Staging'
        if: github.ref == 'refs/heads/main'
        run: |
          aws s3 sync data/guardians/ s3://${{ secrets.STAGING_BUCKET_NAME }}/current/guardians --delete --cache-control max-age=0,no-cache,no-store,must-revalidate
