name: Deploy All (Release)

on:
  # Launches build when release is published
  release:
    types: [ published ]

env:
  REPO_NAME_ALPHANUMERIC: claiming-app-data
  STAGING_BUCKET_NAME: ${{ secrets.STAGING_BUCKET_NAME }}
  PROD_BUCKET_NAME: ${{ secrets.PROD_BUCKET_NAME }}
  INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}

jobs:

  deploy:
    name: Deployment
    runs-on: ubuntu-latest

    steps:

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Remove broken apt repos [Ubuntu]
        if: ${{ matrix.os }} == 'ubuntu-latest'
        run: |
          for apt_file in `grep -lr microsoft /etc/apt/sources.list.d/`; do sudo rm $apt_file; done

      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Configure python environment
        run: |
          sudo apt-get update
          sudo apt-get install --yes --quiet inkscape
          pip install -r requirements.txt

          #- name: 'Process guardian data'
          #if: startsWith(github.ref, 'refs/tags/v')
          #run: |
          #cd guardians
          #python import_guardians.py
          #cd ..

      - name: 'Export vesting data'
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          python vestings/exporter.py --chain-id 1 --output-directory data/allocations
          python vestings/exporter.py --chain-id 5 --output-directory data/allocations

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      # Script to package release files
      - name: 'Package release version'
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          # aws s3 sync data/guardians/ s3://${{ secrets.STAGING_BUCKET_NAME }}/releases/${{ github.event.release.tag_name }}/guardians --delete --cache-control max-age=0,no-cache,no-store,must-revalidate
          aws s3 sync data/allocations/ s3://${{ secrets.STAGING_BUCKET_NAME }}/releases/${{ github.event.release.tag_name }}/allocations --delete --cache-control max-age=0,no-cache,no-store,must-revalidate

      # Script to prepare production deployments
      - name: 'Prepare production deployment flow'
        if: success() && startsWith(github.ref, 'refs/tags/v')
        run: bash ./scripts/github/prepare_production_deployment.sh
        env:
          PROD_DEPLOYMENT_HOOK_TOKEN: ${{ secrets.PROD_DEPLOYMENT_HOOK_TOKEN }}
          PROD_DEPLOYMENT_HOOK_URL: ${{ secrets.PROD_DEPLOYMENT_HOOK_URL }}
          VERSION_TAG: ${{ github.event.release.tag_name }}
