name: Generate Vesting Roots

on:
  # Launches when manually triggered with the new workflow_dispatch event
  workflow_dispatch:
    branches:
      - main
    inputs:
      chain_id:
        type: choice
        description: chain id
        options:
          - 1
          - 5

env:
  REPO_NAME_ALPHANUMERIC: claiming-app-data
  STAGING_BUCKET_NAME: ${{ secrets.STAGING_BUCKET_NAME }}
  PROD_BUCKET_NAME: ${{ secrets.PROD_BUCKET_NAME }}
  INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}

jobs:

  deploy:
    name: Generating Vesting Roots
    runs-on: ubuntu-latest

    steps:

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Remove broken apt repos [Ubuntu]
        if: ${{ matrix.os }} == 'ubuntu-latest'
        run: |
          for apt_file in `grep -lr microsoft /etc/apt/sources.list.d/`; do sudo rm $apt_file; done

      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Configure python environment
        run: |
          pip install -r requirements.txt

      - name: 'Process vesting data'
        if: github.ref == 'refs/heads/main'
        run: |
          cd vestings
          if [[ ${{ github.event.inputs.chain_id }} == 5 ]]; then
            python exporter.py --clear-db --chain-id ${{ github.event.inputs.chain_id }} --process-vestings --generate-root --start-date 1531526400 --duration 416
          else
            python exporter.py --clear-db --chain-id ${{ github.event.inputs.chain_id }} --process-vestings --generate-root
          fi
          cd ..
